name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "e9f95a9cdebc52c62e6250c35e90fee5"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "pastes.lwd-temp.top", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "5c60d72fa9314503bb13c208e4f0a1b5" },
  { binding = "PBIMGS", id ="348bd75d997a4303beae53d3de16629b" }
]

[site]
bucket = "./static/dist"
